### ISSUE TITLE
Dwell time!

### ISSUE THREAD

**Issue by g-s-2018** [smaegol/nanotail#2]
Hi,

I am wondering how nanotail calculate the dwell time in Polya_data table?

Thanks in advance,

**Comment by smaegol** [comment]
Hi,

dwell time is in fact the number of sampling points for the poly(A) tail in the signal. To convert it to the actual time it should be divided by the sampling rate which for RNA should be 3012. 

This is calculated as difference between nanopolish-calculated transcript_start and polya_start https://github.com/smaegol/nanotail/blob/79eb40c1bd666becb47a119cbf970769f04511c5/R/read_polyA_data.R#L34

I use this just for the comparison to calculated poly(A) length.

I hope it helps
